bookyourdoctor/Models/PatientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace bookyourdoctor.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    namespace bookyourdoctor.Models
    {
        public class ExternalLoginConfirmationViewModel
        {
            [Required]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }

        public class ExternalLoginListViewModel
        {
            public string ReturnUrl { get; set; }
        }

        public class SendCodeViewModel
        {
            public string SelectedProvider { get; set; }
            public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
            public string ReturnUrl { get; set; }
            public bool RememberMe { get; set; }
        }

        public class VerifyCodeViewModel
        {
            [Required]
            public string Provider { get; set; }

            [Required]
            [Display(Name = "Code")]
            public string Code { get; set; }
            public string ReturnUrl { get; set; }

            [Display(Name = "Remember this browser?")]
            public bool RememberBrowser { get; set; }

            public bool RememberMe { get; set; }
        }

        public class ForgotViewModel
        {
            [Required]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }

        public class LoginViewModel
        {
            [Required]
            [Display(Name = "Email")]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public class RegisterViewModel
        {
           
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            [StringLength(100, ErrorMessage = "The {0} must be at least {6} characters long.", MinimumLength = 6)]

            public string Name;
            public int PhoneNumber;
           


        }

        public class ResetPasswordViewModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            public string Code { get; set; }
        }

        public class ForgotPasswordViewModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }
    }

}

bookyourdoctor/Controllers/doctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class doctorsController : Controller
    {
        private FINALSCRIPTTEntities1 db = new FINALSCRIPTTEntities1();

        // GET: doctors
        public ActionResult Index()
        {
            return View(db.doctors.ToList());
        }

        // GET: doctors/Details/5
        public ActionResult Details(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }


        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(doctor p)
        {
            using (FINALSCRIPTTEntities1 db = new FINALSCRIPTTEntities1())
            {
                var usr = db.doctors.SingleOrDefault(u => u.doctor_id == p.doctor_id);
                if (usr != null)
                {
                    if (usr.password.ToString() == p.password.ToString())
                    {
                        Session["doctor_id"] = usr.doctor_id.ToString();
                        return RedirectToAction("DoctorWelcome1","doctor_scedule", new { ide = usr.doctor_id.ToString()});

                    }
                }
                else
                {
                    ModelState.AddModelError("", "Email or password is wrong");
                }
            }
            return View(p);

        }

       

        // GET: doctors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "doctor_id,name,date_of_birth,adress,phone,MBBS_Code,email,password,confirm_password,clinic_name,hospital_address,hospital_name,clinic_address,city,specialization,practising_years")] doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }

        //[HttpPost]
        //public ActionResult ViewShedule(string ide, string idee, string ideee, string ad, string add)

        //{
        //doctor dp = new doctor();
        //dp.doctor_id = ide;
        //dp.clinic_name = idee;
        //dp.hospital_name = ideee;
        //dp.hospital_address = add;
        //dp.clinic_address = ad;
        //Session["doctor_id"] = ide;
        //Session["clinic_name"] = idee;
        //Session["hospital_address"] = add;
        //Session["clinic_address"] = ad;

        //    return View(dp);

        //}

        public ActionResult ViewShedule(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }
       





        // GET: doctors/Edit/5
        public ActionResult Edit(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "doctor_id,name,date_of_birth,adress,phone,MBBS_Code,email,password,confirm_password,clinic_name,hospital_address,hospital_name,clinic_address,city,specialization,practising_years")] doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: doctors/Delete/5
        public ActionResult Delete(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string ide)
        {
            doctor doctor = db.doctors.Find(ide);
            db.doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Controllers/patientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class patientsController : Controller
    {
        private FINALSCRIPTTEntities1 db = new FINALSCRIPTTEntities1();

        // GET: patients
        public ActionResult Index()
        {
            return View(db.patients.ToList());
        }

        // GET: patients/Details/5
        public ActionResult Details(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patients.Find(ide);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(patient p)
        {
            using (FINALSCRIPTTEntities1 db = new FINALSCRIPTTEntities1())
            {
                var usr = db.patients.SingleOrDefault(u => u.email == p.email);
                if (usr != null)
                {
                    if (usr.password.Trim().ToString() == p.password.Trim().ToString())
                    {
                        Session["email"] = usr.email.ToString();
                        return RedirectToAction("SelectDoctor");

                    }
                }
                else
                {
                    ModelState.AddModelError("", "Email or password is wrong");
                }
            }
            return View(p);

        }



        public ActionResult SelectDoctor()
        {
            return View();
        }

        public ActionResult ViewDoctorDetails()
        {
            return View();
        }
        public ActionResult TakeAppoitment()
        {
            return View();
        }

        public ActionResult CardiologistsDetails()
        {
            return View();
        }

        public ActionResult ChildSpecialistDetails()
        {
            return View();
        }

        public ActionResult DermatologistDetails()
        {
            return View();
        }
        public ActionResult GynecologistDetails()
        {
            return View();
        }

        public ActionResult DentistDetails()
        {
            return View();
        }
        public ActionResult PsychologistDetails()
        {
            return View();
        }

        public ActionResult ViewShedule(string ide, string idee, string ideee, string ad, string add)
        {
            doctor dp = new doctor();
            dp.doctor_id = ide;
            dp.clinic_name = idee;
            dp.hospital_name = ideee;
            dp.hospital_address = add;
            dp.clinic_address = ad;
            Session["doctor_id"] = ide;
            Session["clinic_name"] = idee;
            Session["hospital_address"] = add;
            Session["clinic_address"] = ad;

            return View(dp);
            
        }



       

        public ActionResult GetHospitalAppoitment()
        {
            return View();
        }



        // GET: patients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "name,email,contact_number,password,Confirm_password")] patient patient)
        {
            if (ModelState.IsValid)
            {
                db.patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: patients/Edit/5
        public ActionResult Edit(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patients.Find(ide);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "name,email,contact_number,password,Confirm_password")] patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: patients/Delete/5
        public ActionResult Delete(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patients.Find(ide);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string ide)
        {
            patient patient = db.patients.Find(ide);
            db.patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Views/patients/CardiologistsDetails.cshtml
@model bookyourdoctor.doctor

@{
    /**/

    ViewBag.Title = "CardiologistsDetails";
}
<body style="background-image:url(../images/cardio.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  height:400px;">
  


    <h2>CardiologistsDetails</h2>
    @{
        doctor dg = new doctor();
        IEnumerable<doctor> lst = dg.doctorsspec("cardiologist");
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()



    <table class="table table-bordered table-condensed">
        <tbody>
            <tr>

                <th style="font-family:Arial;font-size:24px">NAME</th>
                <th style="font-family:Arial;font-size:24px">CLINIC NAME</th>
                <th style="font-family:Arial;font-size:24px">HOSPITAL NAME</th>

                <th style="font-family:Arial;font-size:24px">DETAILS</th>

            </tr>
            @foreach (var item in lst.ToList())
            {
                <tr>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.clinic_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospital_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.ActionLink("Details", "Details", "doctors", new { ide = item.doctor_id }, null)</td>
                </tr>

            }

        </tbody>
    </table>
    }

</body>

bookyourdoctor/Views/patients/ChildSpecialistDetails.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "ChildSpecialist Details";
}

<h2>ChildSpecialistDetails</h2>

<body style="background-image:url(../images/babby.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  height:400px;">
    

    @{
        doctor dg = new doctor();
        IEnumerable<doctor> lst = dg.doctorsspec("Child Specialist");
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


    <table class="table table-bordered table-condensed">
        <tbody>
            <tr>

                <th style="font-family:Arial;font-size:24px">NAME</th>
                <th style="font-family:Arial;font-size:24px">CLINIC NAME</th>
                <th style="font-family:Arial;font-size:24px">HOSPITAL NAME</th>
                <th style="font-family:Arial;font-size:24px">DETAILS</th>

            </tr>
            @foreach (var item in lst.ToList())
            {
                <tr>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.clinic_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospital_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.ActionLink("Details", "Details", "doctors", new { ide = item.doctor_id }, null)</td>
                </tr>

            }

        </tbody>
    </table>
    }

</body>

bookyourdoctor/Views/patients/Delete.cshtml
@model bookyourdoctor.patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contact_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contact_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Confirm_password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Confirm_password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

bookyourdoctor/Views/patients/DentistDetails.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "Dentist Details";
}

<h2>DentistDetails</h2>

<body style="background-image:url(../images/den.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  height:400px;">
   



    @{
        doctor dg = new doctor();
        IEnumerable<doctor> lst = dg.doctorsspec("Dentist");
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <table class="table table-bordered table-condensed">
            <tbody>
                <tr>

                    <th style="font-family:Arial;font-size:24px">NAME</th>
                    <th style="font-family:Arial;font-size:24px">CLINIC NAME</th>
                    <th style="font-family:Arial;font-size:24px">HOSPITAL NAME</th>
                    <th style="font-family:Arial;font-size:24px">DETAILS</th>

                </tr>
                @foreach (var item in lst.ToList())
                {
                    <tr>
                        <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.name)</td>
                        <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.clinic_name)</td>
                        <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospital_name)</td>
                        <td style="font-family:Arial;font-size:24px">@Html.ActionLink("Details", "Details", "doctors", new { ide = item.doctor_id }, null)</td>
                    </tr>

                }

            </tbody>
        </table>
    }

</body>

bookyourdoctor/Views/patients/DermatologistDetails.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "Dermatologist Details";
}

<h2>DermatologistDetails</h2>

<body style="background-image:url(../images/der.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  height:400px;">
    


    
    @{
        doctor dg = new doctor();
        IEnumerable<doctor> lst = dg.doctorsspec("Dermatologist");
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


    <table class="table table-bordered table-condensed">
        <tbody>
            <tr>

                <th style="font-family:Arial;font-size:24px">NAME</th>
                <th style="font-family:Arial;font-size:24px">CLINIC NAME</th>
                <th style="font-family:Arial;font-size:24px">HOSPITAL NAME</th>
                <th style="font-family:Arial;font-size:24px">DETAILS</th>

            </tr>
            @foreach (var item in lst.ToList())
            {
                <tr>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.clinic_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospital_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.ActionLink("Details", "Details", "doctors", new { ide = item.doctor_id }, null)</td>
                </tr>

            }

        </tbody>
    </table>
    }

</body>

bookyourdoctor/Views/patients/GynecologistDetails.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "Gynecologist Details";
}

<h2>GynecologistDetails</h2>

<body style="background-image:url(../images/harmones.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  height:400px;">
    

    
    @{
        doctor dg = new doctor();
        IEnumerable<doctor> lst = dg.doctorsspec("Gynecologist");
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()



    <table class="table table-bordered table-condensed">
        <tbody>
            <tr>

                <th style="font-family:Arial;font-size:24px">NAME</th>
                <th style="font-family:Arial;font-size:24px">CLINIC NAME</th>
                <th style="font-family:Arial;font-size:24px">HOSPITAL NAME</th>
                <th style="font-family:Arial;font-size:24px">DETAILS</th>

            </tr>
            @foreach (var item in lst.ToList())
            {
                <tr>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.clinic_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospital_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.ActionLink("Details", "Details", "doctors", new { ide = item.doctor_id }, null)</td>
                </tr>

            }

        </tbody>
    </table>
    }

</body>

bookyourdoctor/Views/patients/Index.cshtml
@model IEnumerable<bookyourdoctor.patient>

@{
    ViewBag.Title = "Index";
}



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contact_number)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Confirm_password)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        c
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contact_number)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Confirm_password)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", "patients", new { ide = item.email }, null) |
            @Html.ActionLink("Details", "Details", "patients", new { ide = item.email }, null) |
            @Html.ActionLink("Delete", "Delete", "patients", new { ide = item.email }, null)
        </td>
    </tr>
}

</table>

bookyourdoctor/Views/patients/PsychologistDetails.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "Psychologist Details";
}

<h2>PsychologistDetails</h2>

<body style="background-image:url(../images/bran.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  height:400px;">


    
    @{
        doctor dg = new doctor();
        IEnumerable<doctor> lst = dg.doctorsspec("Psychologist");
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


    <table class="table table-bordered table-condensed">
        <tbody>
            <tr>

                <th style="font-family:Arial;font-size:24px">NAME</th>
                <th style="font-family:Arial;font-size:24px">CLINIC NAME</th>
                <th style="font-family:Arial;font-size:24px">HOSPITAL NAME</th>
                <th style="font-family:Arial;font-size:24px">DETAILS</th>

            </tr>
            @foreach (var item in lst.ToList())
            {
                <tr>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.clinic_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospital_name)</td>
                    <td style="font-family:Arial;font-size:24px">@Html.ActionLink("Details", "Details", "doctors", new { ide = item.doctor_id }, null)</td>
                </tr>

            }

        </tbody>
    </table>
    }

</body>

bookyourdoctor/Views/patients/SelectDoctor.cshtml
@{
    ViewBag.Title = "SelectDoctor";
}
<body style="background-image:url(../images/qqq.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  height:400px;">
    <style>

        .square {
            height: 250px;
            width: 300px;
            background-color: white;
            position: relative;
            left: 50px;
            border-radius: 50%;
            top: 45px;
        }

        .square1 {
            height: 250px;
            width: 300px;
            background-color: white;
            position: relative;
            left: 500px;
            border-radius: 50%;
            bottom: 500px;
        }

        .square2 {
            height: 250px;
            width: 300px;
            background-color: white;
            position: relative;
            left: 950px;
            border-radius: 50%;
            bottom: 1030px;
        }
    </style>


    <div class="square" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Cardiologists", "CardiologistsDetails", "patients")</h3>
        <p>
            Cardiology is a branch of medicine<br> dealing with disorders of the heart as<br> well as parts of the circulatory system.<br>
            The field includes medical diagnosis<br> and treatment of congenital heart defects.
        </p>
    </div>
    <div class="square" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Child Specialist", "ChildSpecialistDetails", "patients")</h3>
        <p>
            Child life specialists are <br> pediatric health care professionals<br> who work with children to help<br>them cope with the challenges <br>of hospitalization, illness, and disability..
        </p>
    </div>
    <div class="square1" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Gynecologist", "GynecologistDetails", "patients")</h3>
        <p>
            A gynecologist treats the<br>overall health of their female patients<br>treating problems and diseases of <br>the female reproductive system.<br>A gynecologist is an obstetrician as<br> well.
        </p>
    </div>
    <div class="square1" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Dermatologist", "DermatologistDetails", "patients")</h3>
        <p>
            A dermatologist is a doctor who<br> specializes in the study of skin <br> and the treatment of skin diseases.<br> A physician who specializes in the<br> diagnosis and treatment of skin problems.
        </p>
    </div>
    <div class="square2" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Dentist", "DentistDetails", "patients")</h3>
        <p>
            One who is skilled in and licensed<br> to practice the prevention, diagnosis,<br> and treatment of diseases, injuries,<br> and malformations of the teeth, <br>jaws, and mouth and who makes and<br> inserts false teeth.

        </p>
    </div>
    <div class="square2" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Psychologist", "PsychologistDetails", "patients")</h3>
        <p>
            Clinical psychologists diagnose and<br> treat individuals suffering from<br> psychological distress and mental illness.<br> They also perform psychotherapy and<br> develop treatment plans.
        </p>
    </div>
</body>